export const questions=[
    {
    number:"1",
    title:"Two Sum",
    difficulty:"Easy",
    category:"two pointer",
    statement:"given an array of integers find two elements such that they sum to given element k ",
    solution:"dsad",   
},
{
    number:"2",
    title:"Three Sum",
    difficulty:"Easy",
    category:"two pointer",
    statement:"given an array of integers find two elements such that they sum to given element k ",
    solution:"",   
},
{
    number:"1",
    title:"Two Sum",
    difficulty:"Easy",
    category:"two pointer",
    statement:"given an array of integers find two elements such that they sum to given element k ",
    solution:"dsad",   
},
{
    number:"2",
    title:"Three Sum",
    difficulty:"Easy",
    category:"two pointer",
    statement:"given an array of integers find two elements such that they sum to given element k ",
    solution:"",   
},
{
    number:"1",
    title:"Two Sum",
    difficulty:"Easy",
    category:"two pointer",
    statement:"given an array of integers find two elements such that they sum to given element k ",
    solution:"dsad",   
},
{
    number:"2",
    title:"Three Sum",
    difficulty:"Easy",
    category:"two pointer",
    statement:"given an array of integers find two elements such that they sum to given element k ",
    solution:"",   
},
{
    number:"1",
    title:"Two Sum",
    difficulty:"Easy",
    category:"two pointer",
    statement:"given an array of integers find two elements such that they sum to given element k ",
    solution:"dsad",   
},
{
    number:"2",
    title:"Three Sum",
    difficulty:"Easy",
    category:"two pointer",
    statement:"given an array of integers find two elements such that they sum to given element k ",
    solution:"",   
},
{
    number:"1",
    title:"Two Sum",
    difficulty:"Easy",
    category:"two pointer",
    statement:"given an array of integers find two elements such that they sum to given element k ",
    solution:"dsad",   
},
{
    number:"2",
    title:"Three Sum",
    difficulty:"Easy",
    category:"two pointer",
    statement:"given an array of integers find two elements such that they sum to given element k ",
    solution:"",   
}
]

export default questions;